apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst-console
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://charts.kubefirst.com
    targetRevision: 2.2.7
    chart: kubefirst
    helm:
      values: |-
        kubefirst-api:
          env:
            - name: IN_CLUSTER
              value: "'true'"
        console:
          ingress:
            enabled: "true"
            hosts:
              - host: kubefirst.<DOMAIN_NAME>
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: kubefirst-tls
                hosts:
                  - kubefirst.<DOMAIN_NAME>
          env:
          - name: POSTHOG_KEY
            value: "phc_1i5RDnv8Byf9w05fV8l02GSltpDwF9iyf0ry0U0Fw4r"
  destination:
    server: https://kubernetes.default.svc
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
