apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1000'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_GIT_URL>
    path: registry/<CLUSTER_NAME>/components/development
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kratix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true