apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wildcard
spec:
  acme:
    email: <EMAIL_ADDRESS>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-wildcard
    solvers:
    - selector:
        dnsZones:
          - "<AWS_HOSTED_ZONE_NAME>"
      dns01:
        route53:
          region: <AWS_DEFAULT_REGION>
          hostedZoneID: <AWS_HOSTED_ZONE_ID>
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-wildcard-certificate
spec:
  secretName: wildcard-tls
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-wildcard
  commonName: "*.<AWS_HOSTED_ZONE_NAME>"
  dnsNames:
    - "*.<AWS_HOSTED_ZONE_NAME>"