apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: <WORKLOAD_CLUSTER_NAME>
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "k1-state-store-kgetpods-biz-mktpl-jd-3wzef6"
          key      = "registry/<WORKLOAD_CLUSTER_NAME>/provider-config/terraform.tfstate"
          endpoint = "https://objectstore.LON1.civo.com"

          region = "LON1"

          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          force_path_style            = true
        }
        required_providers {
          civo = {
            source = "civo/civo"
          }
        }
      }
      provider "civo" {
        region = "LON1"
      }
  credentials:
  - filename: gen-nothing
    source: None
    secretRef:
      namespace: crossplane-system
      name: civo-creds
      key: token
