metaphor-frontend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-wildcard"
    hosts:
      - host: metaphor-frontend-production.<AWS_HOSTED_ZONE_NAME>
        paths:
          - /
    tls:
    - secretName: wildcard-tls
      hosts:
        - "*.<AWS_HOSTED_ZONE_NAME>"
  metaphor:
    host: https://metaphor-production.<AWS_HOSTED_ZONE_NAME>
  metaphorGo:
    host: https://metaphor-go-production.<AWS_HOSTED_ZONE_NAME>

