apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: <WORKLOAD_CLUSTER_NAME>
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: <WORKLOAD_CLUSTER_NAME> description
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'git@github.com:kgetpods-biz/gitops.git'
  - 'https://kubernetes.github.io/ingress-nginx'
  - 'https://kubernetes-sigs.github.io/external-dns'
  - 'https://charts.jetstack.io'
  - 'https://charts.external-secrets.io'
  - 'https://stakater.github.io/stakater-charts'
  - 'https://chartmuseum.kgetpods.biz'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: external-dns
    name: <WORKLOAD_CLUSTER_NAME>
  - namespace: <WORKLOAD_CLUSTER_NAME>
    name: <WORKLOAD_CLUSTER_NAME>
  - namespace: external-secrets-operator
    name: <WORKLOAD_CLUSTER_NAME>
  - namespace: reloader
    name: <WORKLOAD_CLUSTER_NAME>
  - namespace: cert-manager
    name: <WORKLOAD_CLUSTER_NAME>
  - namespace: ingress-nginx
    name: <WORKLOAD_CLUSTER_NAME>
  - namespace: kube-system
    name: <WORKLOAD_CLUSTER_NAME>
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: <WORKLOAD_CLUSTER_NAME>-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:<WORKLOAD_CLUSTER_NAME>:admin-role, applications, *, <WORKLOAD_CLUSTER_NAME>/*, allow